### DISCUSSION TITLE
v1.0.0-beta02

### DISCUSSION THREAD

**Discussion by sellmair** [JetBrains/compose-hot-reload#257] [Announcements]
## Beta: Significant Changes
This is the first, publicly announced, beta release of Compose Hot Reload. 

- Stabilized the Gradle API (⚠️ Read about Breaking Changes below)
- Stabilized 'Orchestration Protocol' (⚠️Read about Breaking Changes below)

### Gradle Plugin
- ⚠️ **breaking**: Changed package from `org.jetbrains.compose.reload` to `org.jetbrains.compose.reload.gradle`
- ⚠️ **breaking**: Aligned task naming schema with KGP run tasks
    - from `jvmRunHot` -> `hotRunJvm` (multiplatform)
    - from `runHot` -> `hotRun` (jvm)
- Use `mainClass` from `compose.application` configuration as convention
- Support Gradle 9

### Core
- Removed slf4j dependency in favor of custom logging implementation
    - `compose.reload.logStdout=true`
    - `compose.reload.logLevel=Info`
- Removed 'dev' variant from the runtime artifacts: A single 'main' variant for 'hot-reload-runtime-jvm' is published
- Removed relocation markers for old `artifactId`s

### DevTools
- Fixed 'ReloadState' when using `explicit reload mode`
- Implemented 'coordinated shutdown' to clean up resources when the user application dies
- 

### Analysis
- Improve support for Lambdas: Ignore `ComposableSingletons` when resolving transitively dirty scopes

### Amper
- Added extension point for Amper to take full control over the recompilation

### Compose Multiplatform
- Fix devtools not showing up automatically with Compose Multiplatform 1.9.0-alpha03
- Initial support for changes in compose resources (e.g., adding Strings or Images). Full support (e.g., by automatically refreshing the resources on screen is not yet enabled by default.

#### Why was beta01 not advertised?
The promotion towards beta was rolled out in two phases. `beta01` can be used by clients which are not ready to adapt their build scripts quickly, but require other fixes or functional changes.

<hr /><em>This discussion was created from the release <a href='https://github.com/JetBrains/compose-hot-reload/releases/tag/v1.0.0-beta02'>v1.0.0-beta02</a>.</em>

**Comment by ayitinya** [comment]
Hi, tried updating to `beta02` and got the below error on sync.
`beta01` syncs just fine.

I've attached `libs.versions.toml` for reference.

Is there anything I'm missing.

ps: could also be my exhausted brain
```bash
> Task :buildSrc:compilePluginsBlocks
e: file:///C:/Users/Rudy/.gradle/caches/modules-2/files-2.1/org.jetbrains.compose.hot-reload/hot-reload-annotations-jvm/1.0.0-beta02/74e35efda7d737cefc914b4b4dc8affcf88ad653/hot-reload-annotations-jvm-1.0.0-beta02.jar!/META-INF/hot-reload-annotations.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///C:/Users/Rudy/.gradle/caches/modules-2/files-2.1/org.jetbrains.compose.hot-reload/hot-reload-gradle-plugin/1.0.0-beta02/7d564be96510fcabf572183bd4922d815700c0cd/hot-reload-gradle-plugin-1.0.0-beta02.jar!/META-INF/hot-reload-gradle-plugin.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///C:/Users/Rudy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///C:/Users/Rudy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///C:/Users/Rudy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.

> Task :buildSrc:compilePluginsBlocks FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compilePluginsBlocks'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

```properties
#gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-8.14.2-bin.zip
```

```toml
[versions]
agp = "8.11.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.1"
androidx-constraintlayout = "2.2.1"
androidx-core = "1.16.0"
androidx-espresso = "3.6.1"
androidx-lifecycle = "2.9.1"
androidx-testExt = "1.2.1"
composeHotReload = "1.0.0-beta02"
composeMultiplatform = "1.9.0-alpha02"
junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
ktor = "3.1.3"
sqldelight = "2.1.0"
kotlinx-serialization = "1.8.1"
koin-annotation = "2.1.0"
cupertino = "2.2.5"


[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version = "1.23.8" }
detekt-compose-rules = { module = "io.nlopez.compose.rules:detekt", version = "0.4.22" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.0-beta03" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
koin-bom = { module = "io.insert-koin:koin-bom", version = "4.1.0" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koin-annotation" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotation" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-resources= { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version = "3.1.4" }
supabase-postgres = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
jSystem-theme-detector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version = "3.9.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.0-0.6.x-compat" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detect = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
detektCompiler = { id = "io.github.detekt.gradle.compiler-plugin", version = "1.23.8" }
ksp = { id = "com.google.devtools.ksp", version = "2.2.0-2.0.2" }
sqldelight = { id = "app.cash.sqldelight", version = "2.1.0" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.7" }
```
